### ISSUE TITLE
Hello, can you update to the 4.18.1or 4.18.0, thanks a lot.

### ISSUE THREAD

**Issue by clarkqwang** [ue4plugins/WindowsMessageHandlerExample#1]

**Comment by gmpreussner** [comment]
Done https://github.com/ue4plugins/WindowsMessageHandlerExample/releases/tag/4.18

**Comment by clarkqwang** [comment]
Tanks for update, but there are some errors when I compile the game in  Visual Studio 2017. when i launch the game and rebuild it directly, it show that the file could not be compiled. is there any solution for that, thank you!

**Comment by gmpreussner** [comment]
I can compile without errors in 4.18. Can you please paste your full error messages here?

**Comment by clarkqwang** [comment]
I create a new C++ project in UE4 and add a new folder "Plugins" in the project, then I put the folder "WindowsMessageHandlerExample-4.18" in the "Plugins" folder of my project, and open Visual Studio to build solution.  The VS show some errors .(I do not edit anything in the "WindowsMessageHandlerExample-4.18")    Thanks for your help!
 ------- Error Begin---------------------------------------------


Severity	Code	Description	Project	File	Line	Suppression State
Error	C4596	'ShutdownModule': illegal qualified name in member declaration	MyPluginTest	G:\Example\MyPluginTest\Plugins\WindowsMessageHandlerExample-4.18\Source\WindowsMessageHandlerExample\Private\WindowsMessageHandlerExampleModule.cpp	58	
Error	C4596	'StartupModule': illegal qualified name in member declaration	MyPluginTest	G:\Example\MyPluginTest\Plugins\WindowsMessageHandlerExample-4.18\Source\WindowsMessageHandlerExample\Private\WindowsMessageHandlerExampleModule.cpp	46	
Error		Failed to produce item: G:\Example\MyPluginTest\Plugins\WindowsMessageHandlerExample-4.18\Binaries\Win64\UE4-WindowsMessageHandlerExample-Win64-Shipping.lib	MyPluginTest	G:\Example\MyPluginTest\Intermediate\ProjectFiles\ERROR	1	
Error	MSB3075	The command "E:\UE_4.18\Engine\Build\BatchFiles\Build.bat MyPluginTest Win64 Shipping "G:\Example\MyPluginTest\MyPluginTest.uproject" -waitmutex" exited with code 5. Please verify that you have sufficient rights to run this command.	MyPluginTest	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets	44	

-------------------------Error End------------------------

**Comment by gmpreussner** [comment]
That's definitely a a bug in the code. Not sure how that slipped in. My Visual Studio wasn't complaining either. Can you please try the new 4.18 release? I updated it, thanks!

**Comment by clarkqwang** [comment]
It works now! Thank you!
